version: '3'

services:
  underrule.frontend:
    image: underrule.frontend
    build:
      context: ./UnderRule.FrontEnd
      dockerfile: Dockerfile

  underrule.authentication:
    image: underrule.authentication
    build:
      context: ./UnderRule.Authentication
      dockerfile: Dockerfile

  underrule.worldservice:
    image: underrule.worldservice
    build:
      context: ./UnderRule.WorldService
      dockerfile: Dockerfile

  underrule.playerservice:
    image: underrule.playerservice
    build:
      context: ./UnderRule.PlayerService
      dockerfile: Dockerfile

  underrule.combatservice:
    image: underrule.combatservice
    build:
      context: ./UnderRule.CombatService
      dockerfile: Dockerfile

  underrule.registrationservice:
    image: underrule.registrationservice
    build:
      context: .
      dockerfile: ../UnderRule.RegistrationService/Dockerfile

