version: '3'

services:
  underrule.frontend:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  underrule.authentication:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
