version: '3'

services:
  underrule.frontend:
    image: underrule.frontend
    build:
      context: ./UnderRule.FrontEnd
      dockerfile: Dockerfile

  underrule.authentication:
    image: underrule.authentication
    build:
      context: ./UnderRule.Authentication
      dockerfile: Dockerfile
